package Utils;

import java.awt.EventQueue;
import java.awt.GridLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.awt.event.ActionEvent;


/**
 * Main entry point including database initialization actions and buttons for
 * the execution of the screens. It does not follow MVC because it is only
 * temporary so that during the development it is possible to perform
 * initialization actions.
 */
public class SwingMain {

	private JFrame frame;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() { //NOSONAR autogenerated code
			public void run() {
				try {
					SwingMain window = new SwingMain();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace(); //NOSONAR autogenerated code
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public SwingMain() {
		initialize();
	}

	/**
	 * Initialize the database and contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setTitle("Main");

		frame.setBounds(0, 0, 840, 323);
		frame.setLocationRelativeTo(null);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(new GridLayout(8, 3, 10, 10));

		// Initialize the DB and fill it with data
		Database db = new Database();
		db.createDatabase(false);
		db.loadDatabase();

		// Secretary
		JLabel labelSecretary = new JLabel("Secretary", SwingConstants.CENTER);

		JButton btnRegisterPayments = new JButton("Register a Payment");
		btnRegisterPayments.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				UserStory13575.Controller controller = new UserStory13575.Controller();
				controller.initController();
			}
		});
		JButton btnListFormativeActions = new JButton("List formative actions");
		btnListFormativeActions.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				UserStory13576.Controller controller = new UserStory13576.Controller(new UserStory13576.Model(), new UserStory13576.View());
				controller.initController();
				
			}
		});

		JButton btnStatusOfFormativeActions = new JButton("Status of formative actions");
		btnStatusOfFormativeActions.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				UserStory13577.Controller controller = new UserStory13577.Controller();
				controller.initController();
				
			}
		});

		JButton btnRegisterCancellations = new JButton("Register cancellations");
		btnRegisterCancellations.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				UserStory13578.Controller controller = new UserStory13578.Controller();
				controller.initController();
			}
		});

		JButton btnPayTeacher = new JButton("Pay a teacher");
		btnPayTeacher.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				UserStory13580.Controller controller = new UserStory13580.Controller();
				controller.initController();
			}
		});

		JButton btnDelayFA = new JButton("Delay a Formative Action");
		btnDelayFA.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				UserStory13729.Controller controller = new UserStory13729.Controller();
				controller.initController();
			}
		});

		JButton btnNewButton = new JButton("Cancel a Formative Action");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				UserStory13727.Controller controller = new UserStory13727.Controller();
				controller.initController();
			}
		});

		// Professional
		JLabel labelProfessional = new JLabel("Professional", SwingConstants.CENTER);
		
		JButton btnEnrollInFormativeAction = new JButton("Enroll in formative action");
		btnEnrollInFormativeAction.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				UserStory13574.Controller controller = new UserStory13574.Controller();
				controller.initController();
			}
		});
		
		
		// Training manager
		JLabel labelTrainingManager = new JLabel("Training manager", SwingConstants.CENTER);

		JButton btnPlanFormativeAction = new JButton("Plan formative action");
		btnPlanFormativeAction.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				UserStory13573.Controller controller = new UserStory13573.Controller(new UserStory13573.Model(),
						new UserStory13573.View());
				controller.initController();
			}
		});
		
		JButton btnCheckFinancialBalance = new JButton("Check financial balance");

		btnCheckFinancialBalance.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				UserStory13579.Controller controller;
				try {
					controller = new UserStory13579.Controller(new UserStory13579.Model(), new UserStory13579.View());
					controller.initController();
				} catch (ParseException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});

		// Empty grid elements
		JLabel labelEmpty1 = new JLabel("");
		JLabel labelEmpty2 = new JLabel("");
		JLabel labelEmpty3 = new JLabel("");
		JLabel labelEmpty4 = new JLabel("");
		JLabel labelEmpty5 = new JLabel("");
		JLabel labelEmpty6 = new JLabel("");
		JLabel labelEmpty7 = new JLabel("");
		
		// Add elements to frame/grid
		// Row 1
		frame.getContentPane().add(labelSecretary);
		frame.getContentPane().add(labelProfessional);
		frame.getContentPane().add(labelTrainingManager);
		// Row 2
		frame.getContentPane().add(btnRegisterPayments);
		frame.getContentPane().add(btnEnrollInFormativeAction);
		frame.getContentPane().add(btnPlanFormativeAction);
		// Row 3
		frame.getContentPane().add(btnListFormativeActions);
		frame.getContentPane().add(labelEmpty1);
		frame.getContentPane().add(btnCheckFinancialBalance);
		// Row 4
		frame.getContentPane().add(btnStatusOfFormativeActions);
		frame.getContentPane().add(labelEmpty2);
		frame.getContentPane().add(labelEmpty3);
		// Row 5
		frame.getContentPane().add(btnRegisterCancellations);
		frame.getContentPane().add(labelEmpty4);
		frame.getContentPane().add(labelEmpty5);
		// Row 6
		frame.getContentPane().add(btnPayTeacher);
		frame.getContentPane().add(labelEmpty6);
		frame.getContentPane().add(labelEmpty7);
		
		// Row 7
		frame.getContentPane().add(btnDelayFA);
		
		JLabel label = new JLabel("");
		frame.getContentPane().add(label);
		
		JLabel label_1 = new JLabel("");
		frame.getContentPane().add(label_1);
		
		frame.getContentPane().add(btnNewButton);
	}

	public JFrame getFrame() {
		return this.frame;
	}
}