package Utils;

import java.awt.EventQueue;
import java.awt.GridLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

import UserStory13579.Controller;
import UserStory13579.Model;
import UserStory13579.View;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 * Main entry point including buttons for the execution of the screens. 
 * of the sample applications
 * and database initialization actions.
 * It does not follow MVC because it is only temporary so that during the development it is possible to perform initialization actions.
 * to perform initialization actions
 */
public class SwingMain {

	private JFrame frame;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() { //NOSONAR autogenerated code
			public void run() {
				try {
					SwingMain window = new SwingMain();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace(); //NOSONAR autogenerated code
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public SwingMain() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setTitle("Main");
		frame.setBounds(0, 0, 800,250);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(new GridLayout(6, 4, 10, 10));
				
//		JButton btnExecuteBaseExample = new JButton("Execute the base project");
//		btnExecuteBaseExample.addActionListener(new ActionListener() { //NOSONAR codigo autogenerado
//			public void actionPerformed(ActionEvent e) {
//				CourseController controller=new CourseController(new CourseModel(), new CourseView());
//				controller.initController();
//			}
//		});
//		
//		frame.getContentPane().add(btnExecuteBaseExample);
		
		// DB operations 
		JLabel labelDB = new JLabel("Database operations", SwingConstants.CENTER);
		
		JButton btnInitializeEmptyDatabase = new JButton("Initialize empty data base");
		btnInitializeEmptyDatabase.addActionListener(new ActionListener() { //NOSONAR codigo autogenerado
			public void actionPerformed(ActionEvent e) {
				Database db=new Database();
				db.createDatabase(false);
			}
		});
		
			
		JButton btnLoadTestData = new JButton("Load initial test data");
		btnLoadTestData.addActionListener(new ActionListener() { //NOSONAR codigo autogenerado
			public void actionPerformed(ActionEvent e) {
				Database db=new Database();
				db.createDatabase(false);
				db.loadDatabase();
			}
		});
		
		
		// Secretary
		JLabel labelSecretary = new JLabel("Secretary", SwingConstants.CENTER);
		
		JButton btnRegisterPayments = new JButton("Register Payments");
		
		JButton btnListFormativeActions = new JButton("List formative actions");
		
		JButton btnStatusOfFormativeActions = new JButton("Status of formative actions");
		
		JButton btnRegisterCancellations = new JButton("Register cancellations");
		
		JButton btnRecordPayments = new JButton("Record payments");
		
		// Professional
		JLabel labelProfessional = new JLabel("Professional", SwingConstants.CENTER);
		
		JButton btnEnrollInFormativeAction = new JButton("Enroll in formative action");

		// Training manager
		JLabel labelTrainingManager = new JLabel("Training manager", SwingConstants.CENTER);
		
		JButton btnPlanFormativeAction = new JButton("Plan formative action");
		
		JButton btnCheckFinancialBalance = new JButton("Check financial balance");
		btnCheckFinancialBalance.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Controller controller=new Controller(new Model(), new View());
				controller.initController();
			}
		});

		// Empty grid elements 
		JLabel labelEmpty1 = new JLabel("");
		JLabel labelEmpty2 = new JLabel("");
		JLabel labelEmpty3 = new JLabel("");
		JLabel labelEmpty4 = new JLabel("");
		JLabel labelEmpty5 = new JLabel("");
		JLabel labelEmpty6 = new JLabel("");
		JLabel labelEmpty7 = new JLabel("");
		JLabel labelEmpty8 = new JLabel("");
		JLabel labelEmpty9 = new JLabel("");
		JLabel labelEmpty10 = new JLabel("");
		
		// Add elements to frame/grid 
		// Row 1 
		frame.getContentPane().add(labelDB);
		frame.getContentPane().add(labelSecretary);
		frame.getContentPane().add(labelProfessional);
		frame.getContentPane().add(labelTrainingManager);
		// Row 2 
		frame.getContentPane().add(btnInitializeEmptyDatabase);
		frame.getContentPane().add(btnRegisterPayments);
		frame.getContentPane().add(btnEnrollInFormativeAction);
		frame.getContentPane().add(btnPlanFormativeAction);
		// Row 3 
		frame.getContentPane().add(btnLoadTestData);
		frame.getContentPane().add(btnListFormativeActions);
		frame.getContentPane().add(labelEmpty1);
		frame.getContentPane().add(btnCheckFinancialBalance);
		// Row 4 
		frame.getContentPane().add(labelEmpty2);
		frame.getContentPane().add(btnStatusOfFormativeActions);
		frame.getContentPane().add(labelEmpty3);
		frame.getContentPane().add(labelEmpty4);
		// Row 5 
		frame.getContentPane().add(labelEmpty5);
		frame.getContentPane().add(btnRegisterCancellations);
		frame.getContentPane().add(labelEmpty6);
		frame.getContentPane().add(labelEmpty7);
		// Row 6 
		frame.getContentPane().add(labelEmpty8);
		frame.getContentPane().add(btnRecordPayments);
		frame.getContentPane().add(labelEmpty9);
		frame.getContentPane().add(labelEmpty10);
		
		
	}

	public JFrame getFrame() { return this.frame; }
	
}
