package UserStory13729;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import UserStory13578.Data;

public class Controller {
	private View view;
	private Model model;
	
	public Controller() {
		this.model = new Model();
		model.initModel();
		
		this.view = new View();
		this.initView();
	}

	public void initController() {
		// TODO Auto-generated method stub
		
	}
	
	public void initView() {
		// Open window (replaces the main generated by WindowBuilder)
		view.setVisible(true);

		//view.setTable(getTableModel(model.getAllData()));
	}
	
	public TableModel getTableModel(Data data[]) {
		/*
		 * TableModel tmodel=SwingUtil.getTableModelFromPojos(courses, new String[]
		 * {"id", "name"}); view.getTableCourses().setModel(tmodel);
		 * SwingUtil.autoAdjustColumns(view.getTableCourses());
		 */
		// name of the formative action, the name and email of the professional, the fee
		// paid, the date of the course and the status of the registration
		String header[] = { "Formative Action", "Professional name", "Professional email", "Fee", "Date", "Status" };

		String body[][] = new String[data.length][header.length];

		for (int i = 0; i < data.length; i++) {
			Data d = data[i];
			body[i] = new String[] {
					d.formativeAction.getName(),
					d.professional.getName(),
					d.professional.getEmail(),
					Float.toString(d.formativeAction.getFee()),
					d.formativeAction.getFaStart().toString(),
					d.enrollment.getStatus().toString() };
		}

		TableModel tm = new DefaultTableModel(header, body.length);
		// loads each of the pojos values using PropertyUtils (from apache coommons
		// beanutils)
		for (int i = 0; i < body.length; i++) {
			for (int j = 0; j < header.length; j++) {
				tm.setValueAt(body[i][j], i, j);
			}
		}

		return tm;
	}
}
