package UserStory13729;

import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import Entities.FormativeAction;

public class Controller {
	private View view;
	private Model model;
	
	public Controller() {
		this.model = new Model();
		try {
			model.initModel();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		this.view = new View();
		this.initView();
	}

	public void initController() {
		// TODO Auto-generated method stub
	
	}
	
	public void initView() {
		// Open window (replaces the main generated by WindowBuilder)
		view.setVisible(true);

		view.setTable(getTableModel(model.getAllData()));
	}
	
	public TableModel getTableModel(FormativeAction data[]) {
		String header[] = { "Formative Action", "Date", "Status" };

		String body[][] = new String[data.length][header.length];

		for (int i = 0; i < data.length; i++) {
			FormativeAction d = data[i];
			body[i] = new String[] {
					d.getName(),
					d.getFaStart().toString(),
					d.getStatus().toString() };
		}

		TableModel tm = new DefaultTableModel(header, body.length);

		for (int i = 0; i < body.length; i++) {
			for (int j = 0; j < header.length; j++) {
				tm.setValueAt(body[i][j], i, j);
			}
		}

		return tm;
	}
}
