package UserStory13579;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.List;

import javax.swing.table.TableModel;

import PL53.util.Date;
import Utils.SwingUtil;

public class Controller{
	private Model model;
	private View view;

	public Controller(UserStory13579.Model model, UserStory13579.View view){
		this.model = model;
		this.view = view;
		//no model-specific initialization, only view-specific initialization
		this.initView();
	}
	/**
	 * Controller initialization: add event handlers to the UI objects.
	 * Each event handler is instantiated in the same way, so that it invokes a private method of this handler, enclosed in a generic exception handler to display windows.
	 * Each event handler is instantiated in the same way, so that it invokes a private method of this controller, enclosed in a generic exception handler to display popup windows when a problem or exception occurs.
	 * popup windows when a problem or controlled exception occurs.
	 */
	public void initController() {
		view.getBtnApplyFilter().addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				Date start = new Date(1,1,1000);
				Date end = new Date(1, 1, 10000);
				String status = null; 
				if (view.getFilterStartDate())
					start = view.getStartDate();
				if (view.getFilterEndDate())
					end = view.getEndDate();
				if (view.getFilterStatus())
					status = view.getStatus();
				getBalances(start, end, status);
			}
		});
	}
	
	public void initView(){
		// Update the view data
		this.getBalances(view.getStartDate(), view.getEndDate(), null);
		
		//Open window (replaces the main generated by WindowBuilder)
		view.getFrame().setVisible(true); 
	}
	
	
	/**
	 * Getting the list of financial balance objects & a total balance object list from the model 
	 * and use SwingUtil method to create 2 tablemodels which are finally assigned to the tables.
	 * @throws ParseException 
	 */
	public void getBalances(Date startDate,Date endDate, String status){
		
		// Financial Balance for each formative action 
		List<FinancialBalance> financialBalances = model.getListFinancialBalance(startDate, endDate, status);
		TableModel tmodel=SwingUtil.getTableModelFromPojos(financialBalances, new String[] {"name", "status", "firstSession", "lastSession", "incomeConfirmed", "expensesConfirmed", "balanceConfirmed", "incomeEstimated", "expensesEstimated", "balanceEstimated"}, new String[] {"Name", "Status", "First Session", "Last Session" ,"Income Confirmed", "Expenses Confirmed", "Balance Confirmed", "Income Estimated", "Expenses Estimated", "Balance Estimated"}, true);
		view.getTableFormativeActionBalance().setModel(tmodel);
		SwingUtil.autoAdjustColumns(view.getTableFormativeActionBalance());
		
		// Total Balance 
		List<TotalBalance> totalBalance = model.getListTotalBalance(startDate, endDate, status);
		TableModel tmodelTotal=SwingUtil.getTableModelFromPojos(totalBalance, new String[] {"totalIncomeConfirmed", "totalExpensesConfirmed", "totalIncomeEstimated", "totalExpensesEstimated"}, new String[] {"Total Income Confirmed", "Total Expenses Confirmed", "Total Income Estimated", "Total Expenses Estimated"}, false);
		view.getTableTotalBalance().setModel(tmodelTotal);
		SwingUtil.autoAdjustColumns(view.getTableTotalBalance());
	}
	
}
